#pragma once
#include <iostream>
#include "ZrodloSygnalu.h"
#include "Wyswietlacz.h"
#include "Komputer.h"
#include "Monitor.h"
#include "Rzutnik.h"
#include "TelewizorLCD.h"
#include "OdtwarzaczDVD.h"